### ISSUE TITLE
lock error

### ISSUE THREAD

**Issue by July-X** [PacktPublishing/Concurrent-Patterns-and-Best-Practices#1]
https://github.com/PacktPublishing/Concurrent-Patterns-and-Best-Practices/blob/74abdd3f6f33c7ea3ae1b1ff5300dc7498dfc7ce/src/main/java/com/concurrency/book/chapter05/ThreadSafeQueue.java#L56

this line is need unlock

**Comment by deepesh-packt** [comment]
Hey @July-X ,
https://github.com/PacktPublishing/Concurrent-Patterns-and-Best-Practices/blob/6db07a53175eac16c43a7d62e2652d6e40c829c8/src/main/java/com/concurrency/book/chapter05/ThreadSafeQueue.java#L56
The issue has been resolved. Thanks for highlighting the issue. 
Greetings!
